rename_names = {
    "angola": "Angola",
    "benin": "Benin",
    "burkina_faso": "Burkina Faso",
    "burundi": "Burundi",
    "cameroon": "Cameroon",
    "central_african_republic": "Central African Republic",
    "chad": "Chad",
    "comoros": "Comoros",
    "democratic_republic_of_congo": "Democratic Republic of the Congo",
    "egypt": "Egypt",
    "eswatini": "Eswatini",
    "ethiopia": "Ethiopia",
    "gabon": "Gabon",
    "ghana": "Ghana",
    "guinea": "Guinea",
    "ivory_coast": "Côte d'Ivoire",
    "kenya": "Kenya",
    "lesotho": "Lesotho",
    "liberia": "Liberia",
    "madagascar": "Madagascar",
    "malawi": "Malawi",
    "mali": "Mali",
    "morocco": "Morocco",
    "mozambique": "Mozambique",
    "namibia": "Namibia",
    "niger": "Niger",
    "nigeria": "Nigeria",
    "rwanda": "Rwanda",
    "senegal": "Senegal",
    "sierra_leone": "Sierra Leone",
    "south_africa": "South Africa",
    "tanzania": "Tanzania",
    "togo": "Togo",
    "uganda": "Uganda",
    "zambia": "Zambia",
    "zimbabwe": "Zimbabwe"
}

iso_a3_codes = {
    "angola": "AGO",
    "benin": "BEN",
    "burkina_faso": "BFA",
    "burundi": "BDI",
    "cameroon": "CMR",
    "central_african_republic": "CAF",
    "chad": "TCD",
    "comoros": "COM",
    "democratic_republic_of_congo": "COD",
    "egypt": "EGY",
    "eswatini": "SWZ",
    "ethiopia": "ETH",
    "gabon": "GAB",
    "ghana": "GHA",
    "guinea": "GIN",
    "ivory_coast": "CIV",
    "kenya": "KEN",
    "lesotho": "LSO",
    "liberia": "LBR",
    "madagascar": "MDG",
    "malawi": "MWI",
    "mali": "MLI",
    "morocco": "MAR",
    "mozambique": "MOZ",
    "namibia": "NAM",
    "niger": "NER",
    "nigeria": "NGA",
    "rwanda": "RWA",
    "senegal": "SEN",
    "sierra_leone": "SLE",
    "south_africa": "ZAF",
    "tanzania": "TZA",
    "togo": "TGO",
    "uganda": "UGA",
    "zambia": "ZMB",
    "zimbabwe": "ZWE"
}